print("================================")
print("ECONOMIA")
print("================================")
print()
print("1. Microecnomia")
print("2. Macroecnomia")
print("3. Econometria")
print("4. Estadistica")
print("5. Matematicas")
print("6. Contabilidad")
print("7. Finanzas")
print("8. Ingenieria economica")
print("9. Politica Economica")
print("10. Teoria de Juegos")
print()
print("11. Ejercicios")
print("12. Calculadora")
print("13. Graficas")
print("================================")
