name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev \
            libncursesw5-dev cmake libffi-dev \
            libssl-dev
     
      - name: Instalar Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
   
      - name: Instalar Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install "cython==0.29.37"

      - name: Compilar APK
        run: |
          buildozer android debug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Economia-APK
          path: bin/*.apk
